# Generated by Django 2.2.19 on 2022-10-19 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220813_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Слишком маленькое время приготовления'), django.core.validators.MaxValueValidator(500, 'Макс. время приготовления - 600 минут')], verbose_name='Время приготовления в минутах'),
        ),
    ]
